language: "node_js"
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"


before_install:
  - "npm install -g istanbul@0.4"
  - "npm install -g codecov@3"

script:
  - "make check"

after_success:
  - "make report-cov"

sudo: false
